### ISSUE TITLE
RollbarFlutter.run is limiting (and probably not working as intended)

### ISSUE THREAD

**Issue by rfuerst87** [rollbar/rollbar-flutter#90]
The current design of RollbarFlutter makes it impossible to integrate it with custom error handlers. Especially `FlutterRollbar.run` is very limiting. IMHO it has several issues:

1. `RollbarFlutter` overwrites `FlutterError.onError` without any warnings. Having a custom `onError` function is not compatible with `RollbarFlutter`.
2.  There is no way to just initialize Rollbar without running an app. This basically makes `RollbarFlutter` incompatible with any other error handler.
3. `RollbarFlutter` is creating it's own guarded zone without the possibility to bubble up errors. `FlutterRollbar` swallows all the errors without giving other error handlers a chance to catch an error.
4. `WidgetsFlutterBinding.ensureInitialized()` is called in the wrong place. When initializing a guarded zone `WidgetsFlutterBinding.ensureInitialized()` must be called within that zone. Calling it outside (as it is done in `run`) causes the guarded zone to not catch errors. At this point I think catching async errors does not properly work. Said that, with the current design one has to ensure `WidgetsFlutterBinding.ensureInitialized()` is not called manually before running `RollbarFlutter.run`.

In my eyes the design of `RollbarFlutter.run` is flawed. While the intention to make it as easy to integrate as possible is good, but it also bears the downside of inflexibility. Instead `RollbarFlutter` should expose an API to initialize Rollbar and let the user decide how to implement. Something like this could work for example:

```dart
void main() async {
 
  runZonedGuarded<Future<void>>(() async {
    // let the user be responsible for the guarded zone to 
    // properly run WidgetsFlutterBinding.ensureInitialized()
    WidgetsFlutterBinding.ensureInitialized();

    // Initialize rollbar
    await RollbarFlutter.initialize();
    
    // Give the users a chance to implement their own onError
    FlutterError.onError = RollbarFlutter.onError;

    runApp(MyApp());
  }, (exception, stackTrace) {
    // Also give the users a chance to do anything else with async errors
    RollbarFlutter.error(exception, stackTrace));
  }
}
```

For convenience one could provide simple helper methods in `RollbarFlutter` to make this an one-liner again. I'm not sure whether this is needed to be honest.

Please let me know what you think. I'd offer my support here to come up with an improved version. We are currently forced to work with a fork which I'd get rid of better sooner than later.

**Comment by rollbar-bborsits** [comment]
Hey @rfuerst87, I appreciate that you shared your concerns in a very detailed manner.  I'll talk to the dev team about your comments.

**Comment by mazen930** [comment]
Any updates here ? , as this become more and more serious since i moved to use 3.10 flutter sdk , it throws random errors and not stable

**Comment by mazen930** [comment]
@rfuerst87 is there any work around here ?

**Comment by rollbar-bborsits** [comment]
Hey @mazen930, Thanks for reporting this issue. Can you share what errors Flutter throws?

**Comment by mrchenmo** [comment]
> Hey @mazen930, Thanks for reporting this issue. Can you share what errors Flutter throws? Do you use the latest Rollbar Flutter SDK (v1.3.0)?

The following assertion was thrown during runApp:
Zone mismatch.

The Flutter bindings were initialized in a different zone than is now being used. This will likely cause confusion and bugs as any zone-specific configuration will inconsistently use the configuration of the original binding initialization zone or this zone based on hard-to-predict factors such as which zone was active when a particular callback was set.
It is important to use the same zone when calling `ensureInitialized` on the binding as when calling `runApp` later.
To make this warning fatal, set BindingBase.debugZoneErrorsAreFatal to true before the bindings are initialized (i.e. as the first statement in `void main() { }`).
When the exception was thrown, this was the stack: 
#0      BindingBase.debugCheckZone.<anonymous closure> (package:flutter/src/foundation/binding.dart:497:29)
#1      BindingBase.debugCheckZone (package:flutter/src/foundation/binding.dart:502:6)
#2      runApp (package:flutter/src/widgets/binding.dart:1080:18)
#3      main.<anonymous closure> (package:flutter_app/main.dart:22:42)
#4      RollbarFlutter.run.<anonymous closure> (package:rollbar_flutter/src/rollbar.dart:53:22)
<asynchronous suspension>
#5      RollbarFlutter.run (package:rollbar_flutter/src/rollbar.dart:47:5)
<asynchronous suspension>
#6      main (package:flutter_app/main.dart:22:3)
<asynchronous suspension>

**Comment by mrchenmo** [comment]
The 3.10 version of the SDK restricts the call of ensureInitialized, which must be called after runApp to ensure that it runs in the same Zone as the app. In the code of rollbar, the ensureInitialized method is called before runApp

**Comment by rollbar-bborsits** [comment]
Got it, thanks for the clarification. Let me take this back to the developers.

**Comment by matux** [comment]
With regards to @rfuerst87, I know it's been quite a few months, but I believe your changes to be worth implementing.

I wouldn't want to break userspace if someone decides to upgrade from 1.3.0 to 1.4.0, so I'd approach this as an alternative (more advanced) way of initializing Rollbar Flutter.

What do you think? If you've already forgotten about this, no problem, I will implement your suggestions one way or another.

**Comment by rfuerst87** [comment]
I guess it's important to mention that starting from Flutter 3.3 you souldn't use `runZonedGuarded` to catch errors in flutter anymore. Instead `PlatformDispatcher.onError` is now the recommended approach.

See [What's new in Flutter 3.3](https://medium.com/flutter/whats-new-in-flutter-3-3-893c7b9af1ff#:~:text=In%20this%20release%2C%20instead%20of%20using%20a%20custom%20Zone%2C%20you%20should%20catch%20all%20errors%20and%20exceptions%20by%20setting%20the%20PlatformDispatcher.onError%20callback) and [Handling Errors in Flutter docs](https://docs.flutter.dev/testing/errors) .

**Comment by matux** [comment]
> I guess it's important to mention that starting from Flutter 3.3 you souldn't use `runZonedGuarded` to catch errors in flutter anymore. Instead `PlatformDispatcher.onError` is now the recommended approach.
> 
> See [What's new in Flutter 3.3](https://medium.com/flutter/whats-new-in-flutter-3-3-893c7b9af1ff#:~:text=In%20this%20release%2C%20instead%20of%20using%20a%20custom%20Zone%2C%20you%20should%20catch%20all%20errors%20and%20exceptions%20by%20setting%20the%20PlatformDispatcher.onError%20callback) and [Handling Errors in Flutter docs](https://docs.flutter.dev/testing/errors) .

I made this into a new issue @ https://github.com/rollbar/rollbar-flutter/issues/101, I appreciate the advice!

**Comment by mazen930** [comment]
@rollbar-bborsits  the error is as @matux  mention above

**Comment by mazen930** [comment]
@matux  unfortunately it didn't work (same error exist) , do i need to edit anything rather than just update ?

**Comment by matux** [comment]
@mazen930 no, you shouldn't have to make any changes. Could you confirm you have the latest version 1.3.1?

The SDK example used to crash with this error and is working fine now, so I suspect you might not using be the latest.

**Comment by Nico04** [comment]
Any update on this?
In my case I'd like to debugPrint each error but it's swallowed by the run command.
